version: 2
updates:
- package-ecosystem: npm
  directory: "/bootbox"
  directory: "/open-all-link-to-default-browser"
  directory: "/open-directory"
  directory: "/parent-child-window"
  directory: "/shelljs-command"
  directory: "/vue-bootstrap"
  directory: "/menuitem"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
