version: 2.1
      
jobs:
  build:
    working_directory: ~/electron-example
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"   
      - run:
          name: Install Dependencies
          working_directory: ~/electron-example/bootbox
          command: npm install
      - run:
          name: Run tests
          working_directory: ~/electron-example/bootbox
          command: npm run test