version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            ls
# jobs:
#   build:
#     working_directory: ~/electron-example
#     docker:
#       - image: circleci/node:11-browsers
#     steps:
#       - checkout
#       - run:
#         name: check list
#         command: "ls"
      # - run:
      #     name: Update NPM
      #     command: "sudo npm install -g npm"
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run:
      #     name: Install Dependencies
      #     command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
      # - run:
      #     name: Run tests
      #     command: npm run test