# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: polymer3

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install package
      working-directory: ./polymer3
      run: npm install
    - name: build polymer3
      working-directory: ./polymer3
      run: polymer build
    - name: npm install build polymer3
      working-directory: ./polymer3/build/es6-bundled
      run: npm install --only=prod
